### ISSUE TITLE
Versioning of commits made to the lpdc 

### ISSUE THREAD

**Issue by fmeiners** [yovisto/dwerft#3]
A versioning system is required to ensure (possibly faulty) commits do not overwrite existing data required by other tools.

**Comment by santifa** [comment]
If we use tailr.s16a.org we could do the update process over the versioned rdf files.
The update process should look like
  1. compare new file against version head
  2. create an update file (what to delete, update, replace etc.)
  3. update the triple store accordingly
  4. iff success check in new rdf file else revert

**Comment by santifa** [comment]
With the usage of tailr. This issue can be closed.
